name: ARQUITECTURA ABIERTA
favicon: null
layout_spectrum: 0.24971
typography_spectrum: 0.49327
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3070973420981318
  lightness: 0.7799456412903965
  saturation: 0.3620108475442976
  rhythmicContrast: 0.06577658746391535
purpose: []
